# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bloogui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1212, 636)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(65, 69, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(70, 40))
        self.frame.setStyleSheet("background-color: rgb(222, 184, 135);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_toggle = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_toggle.setStyleSheet("background-color: rgb(117, 80, 123);\n"
"font: 75 11pt \"Ubuntu Mono\";")
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_2.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_toggle = QtWidgets.QFrame(self.top_bar)
        self.frame_toggle.setStyleSheet("background-color: rgb(222, 184, 135);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.verticalLayout.addWidget(self.top_bar)
        self.containt = QtWidgets.QFrame(self.centralwidget)
        self.containt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containt.setObjectName("containt")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.containt)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.containt)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(1, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(1, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgba(85, 87, 83,100);\n"
"background-color: rgba(222, 184, 135,100);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menu = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menu.setStyleSheet("\n"
"background-color: rgb(222, 184, 135);")
        self.frame_top_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menu.setObjectName("frame_top_menu")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_top_menu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.frame_top_menu)
        self.widget.setObjectName("widget")
        self.title = QtWidgets.QLabel(self.widget)
        self.title.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.title.setStyleSheet("font: 25 10pt \"Ubuntu\";")
        self.title.setObjectName("title")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setGeometry(QtCore.QRect(7, 80, 181, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.to_incomme_progress = QtWidgets.QLabel(self.widget)
        self.to_incomme_progress.setGeometry(QtCore.QRect(10, 60, 161, 20))
        self.to_incomme_progress.setTextFormat(QtCore.Qt.AutoText)
        self.to_incomme_progress.setObjectName("to_incomme_progress")
        self.cash = QtWidgets.QLabel(self.widget)
        self.cash.setGeometry(QtCore.QRect(10, 230, 61, 31))
        self.cash.setObjectName("cash")
        self.cash_value = QtWidgets.QLabel(self.widget)
        self.cash_value.setGeometry(QtCore.QRect(100, 230, 81, 21))
        self.cash_value.setObjectName("cash_value")
        self.T_income = QtWidgets.QLabel(self.widget)
        self.T_income.setGeometry(QtCore.QRect(10, 270, 71, 31))
        self.T_income.setStyleSheet("font: 25 italic 9pt \"Ubuntu\";")
        self.T_income.setObjectName("T_income")
        self.t_Expense = QtWidgets.QLabel(self.widget)
        self.t_Expense.setGeometry(QtCore.QRect(10, 300, 71, 31))
        self.t_Expense.setStyleSheet("font: 25 italic 9pt \"Ubuntu\";")
        self.t_Expense.setObjectName("t_Expense")
        self.cash_value_2 = QtWidgets.QLabel(self.widget)
        self.cash_value_2.setGeometry(QtCore.QRect(120, 270, 61, 21))
        self.cash_value_2.setObjectName("cash_value_2")
        self.cash_value_3 = QtWidgets.QLabel(self.widget)
        self.cash_value_3.setGeometry(QtCore.QRect(120, 300, 61, 21))
        self.cash_value_3.setObjectName("cash_value_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(300, 10, 341, 341))
        self.widget_2.setObjectName("widget_2")
        self.inc_table = QtWidgets.QTableWidget(self.widget_2)
        self.inc_table.setGeometry(QtCore.QRect(0, 31, 341, 91))
        self.inc_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inc_table.setObjectName("inc_table")
        self.inc_table.setColumnCount(4)
        self.inc_table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table.setHorizontalHeaderItem(3, item)
        self.INCOME = QtWidgets.QLabel(self.widget_2)
        self.INCOME.setGeometry(QtCore.QRect(0, 0, 341, 31))
        self.INCOME.setStyleSheet("font: 25 11pt \"Ubuntu\";\n"
"color: rgb(238, 238, 236);\n"
"background-color: rgb(117, 80, 123);")
        self.INCOME.setObjectName("INCOME")
        self.EXPENSE = QtWidgets.QLabel(self.widget_2)
        self.EXPENSE.setGeometry(QtCore.QRect(0, 129, 331, 21))
        self.EXPENSE.setStyleSheet("font: 25 11pt \"Ubuntu\";\n"
"color: rgb(238, 238, 236);\n"
"background-color: rgb(117, 80, 123);")
        self.EXPENSE.setObjectName("EXPENSE")
        self.inc_table_2 = QtWidgets.QTableWidget(self.widget_2)
        self.inc_table_2.setGeometry(QtCore.QRect(0, 150, 331, 191))
        self.inc_table_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inc_table_2.setObjectName("inc_table_2")
        self.inc_table_2.setColumnCount(3)
        self.inc_table_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inc_table_2.setHorizontalHeaderItem(2, item)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 340, 641, 251))
        self.widget_3.setObjectName("widget_3")
        self.ASSETS = QtWidgets.QLabel(self.widget_3)
        self.ASSETS.setGeometry(QtCore.QRect(0, 10, 321, 31))
        self.ASSETS.setStyleSheet("font: 25 11pt \"Ubuntu\";\n"
"color: rgb(238, 238, 236);\n"
"background-color: rgb(117, 80, 123);")
        self.ASSETS.setObjectName("ASSETS")
        self.LIABILITIES = QtWidgets.QLabel(self.widget_3)
        self.LIABILITIES.setGeometry(QtCore.QRect(320, 10, 311, 31))
        self.LIABILITIES.setStyleSheet("font: 25 11pt \"Ubuntu\";\n"
"color: rgb(238, 238, 236);\n"
"background-color: rgb(117, 80, 123);")
        self.LIABILITIES.setObjectName("LIABILITIES")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 41, 311, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(320, 40, 311, 211))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_top_menu)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.containt)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 0, 871, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.containt)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_toggle.setText(_translate("MainWindow", "fin_st"))
        self.title.setText(_translate("MainWindow", "   BLOOMING GAME"))
        self.to_incomme_progress.setText(_translate("MainWindow", "TOTAL EXPENSE : $"))
        self.cash.setText(_translate("MainWindow", "CASH:"))
        self.cash_value.setText(_translate("MainWindow", "$"))
        self.T_income.setText(_translate("MainWindow", "totat income :"))
        self.t_Expense.setText(_translate("MainWindow", "totat Expense   :"))
        self.cash_value_2.setText(_translate("MainWindow", "$"))
        self.cash_value_3.setText(_translate("MainWindow", "$"))
        item = self.inc_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "work"))
        item = self.inc_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "divided"))
        item = self.inc_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "real estate"))
        item = self.inc_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.inc_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.inc_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.inc_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Salary"))
        self.INCOME.setText(_translate("MainWindow", "INCOME"))
        self.EXPENSE.setText(_translate("MainWindow", "EXPENSE"))
        item = self.inc_table_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.inc_table_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.inc_table_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        self.ASSETS.setText(_translate("MainWindow", "  ASSETS"))
        self.LIABILITIES.setText(_translate("MainWindow", "  LIABILITIES"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))

