# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
from Choose_dream import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.uic import loadUi
from DATA.data_access import  *
from bloogui import *
from model.Player import *
import  Ui_fonction


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1428, 867)
        #MainWindow.showFullScreen()
        MainWindow.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(173, 127, 168);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_btn_toggle = QtWidgets.QFrame(self.top_bar)
        self.frame_btn_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_btn_toggle.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.frame_btn_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btn_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_toggle.setObjectName("frame_btn_toggle")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_btn_toggle)
        self.btn_toggle.setGeometry(QtCore.QRect(0, -1, 70, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("border:0px solid\n"
"")
        self.btn_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setIconSize(QtCore.QSize(76, 50))
        self.btn_toggle.setAutoRepeat(False)
        self.btn_toggle.setObjectName("btn_toggle")
        self.horizontalLayout.addWidget(self.frame_btn_toggle)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.EXIT = QtWidgets.QPushButton(self.frame_top)
        self.EXIT.setGeometry(QtCore.QRect(1320, 0, 40, 40))
        self.EXIT.setMaximumSize(QtCore.QSize(40, 40))
        self.EXIT.setStyleSheet("border:0px solid")
        self.EXIT.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EXIT.setIcon(icon1)
        self.EXIT.setIconSize(QtCore.QSize(40, 20))
        self.EXIT.setAutoExclusive(False)
        self.EXIT.setObjectName("EXIT")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.pushButton_11.setStyleSheet("border-radius:200px;\n"
"background-color: rgb(114, 159, 207);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.layoutWidget = QtWidgets.QWidget(self.frame_top)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 21, 16))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutWidget.raise_()
        self.EXIT.clicked.connect(app.exit)
        self.pushButton_11.raise_()
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgba(173, 127, 168,60);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMaximumSize(QtCore.QSize(1, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 100), stop:1 rgba(255, 178, 102, 100));")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 100), stop:1 rgba(255, 178, 102, 100));")
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.frame_top_menus)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 100), stop:1 rgba(255, 178, 102, 100));")
        self.widget.setObjectName("widget")
        self.TOTAL_EXPENSE = QtWidgets.QLabel(self.widget)
        self.TOTAL_EXPENSE.setGeometry(QtCore.QRect(455, 85, 16, 17))
        self.TOTAL_EXPENSE.setText("")
        self.TOTAL_EXPENSE.setObjectName("TOTAL_EXPENSE")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 701, 771))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("background-color: rgb(117, 80, 123);\n"
"font: 57 italic 17pt \"Ubuntu\";\n"
"color: rgb(238, 238, 236);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:1 rgba(255, 178, 102, 255));")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(32, 74, 135))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.verticalLayout_11.addWidget(self.tableWidget)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setStyleSheet("font: 57 italic 16pt \"Ubuntu\";\n"
"background-color: rgb(117, 80, 123);\n"
"color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:1 rgba(255, 178, 102, 255));")
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.verticalLayout_11.addWidget(self.tableWidget_2)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_11)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(9, 9, 9, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(-1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_15.addWidget(self.label_5)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.passiv_income = QtWidgets.QProgressBar(self.layoutWidget1)
        self.passiv_income.setProperty("value", 24)
        self.passiv_income.setObjectName("passiv_income")
        self.verticalLayout_14.addWidget(self.passiv_income)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.CASH = QtWidgets.QLabel(self.layoutWidget1)
        self.CASH.setObjectName("CASH")
        self.verticalLayout_12.addWidget(self.CASH)
        self.TOTAL_INCOME = QtWidgets.QLabel(self.layoutWidget1)
        self.TOTAL_INCOME.setObjectName("TOTAL_INCOME")
        self.verticalLayout_12.addWidget(self.TOTAL_INCOME)
        self.TOTAL_EXOENSE = QtWidgets.QLabel(self.layoutWidget1)
        self.TOTAL_EXOENSE.setObjectName("TOTAL_EXOENSE")
        self.verticalLayout_12.addWidget(self.TOTAL_EXOENSE)
        self.PAYDAY = QtWidgets.QLabel(self.layoutWidget1)
        self.PAYDAY.setObjectName("PAYDAY")
        self.verticalLayout_12.addWidget(self.PAYDAY)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_15)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet("background-color: rgb(92, 53, 102);\n"
"color: rgb(238, 238, 236);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:1 rgba(255, 178, 102, 255));")
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget_3.setItem(3, 1, item)
        self.horizontalLayout_4.addWidget(self.tableWidget_3)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:1 rgba(255, 178, 102, 255));")
        self.tableWidget_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_4.setItem(4, 0, item)
        self.horizontalLayout_4.addWidget(self.tableWidget_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.frame_top_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setStyleSheet("QFrame#frame_pages{\n"
"border-image: url(:/icons/images.jpeg);\n"
"}")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.boardgame = QtWidgets.QLabel(self.frame_pages)
        self.boardgame.setGeometry(QtCore.QRect(80, 50, 961, 591))
        self.boardgame.setStyleSheet("border-image: url(:/icons/board/hqdefault.jpg);\n"
"\n"    
"border-radius:20px;")
        self.player = QtWidgets.QPushButton(self.frame_pages)
        self.player.setGeometry(QtCore.QRect(320, 490, 16, 16))
        self.player.setStyleSheet("border-radius:200px;\n"
                                  "background-color: rgb(114, 159, 207);")
        self.player.setText("")
        self.player.setObjectName("player")
        self.boardgame.setText("")
        self.boardgame.setObjectName("boardgame")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_pages)
        self.pushButton_12.setGeometry(QtCore.QRect(320, 490, 16, 16))
        self.pushButton_12.setStyleSheet("border-radius:200px;\n"
"background-color: rgb(114, 159, 207);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_4 = QtWidgets.QLabel(self.frame_pages)
        self.label_4.setGeometry(QtCore.QRect(1090, 630, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.label_4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.frame_stacked = QtWidgets.QFrame(self.frame_pages)
        self.frame_stacked.setGeometry(QtCore.QRect(1050, 50, 371, 461))
        self.frame_stacked.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_stacked.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_stacked.setObjectName("frame_stacked")
        self.game_stacked = QtWidgets.QStackedWidget(self.frame_stacked)
        self.game_stacked.setGeometry(QtCore.QRect(0, 0, 371, 471))
        self.game_stacked.setObjectName("game_stacked")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.game_stacked.addWidget(self.page)
        self.page_2 = QtWidgets.QFrame()
        ui = Ui_dream_label()
        ui.setupUi(self.page_2)

        self.page_2.setObjectName("page_2")
        self.game_stacked.addWidget(self.page_2)
        self.game_stacked.setCurrentIndex(self.game_stacked.currentIndex() + 1)
        self.label_4.raise_()
        self.boardgame.raise_()
        self.pushButton_12.raise_()
        self.frame_stacked.raise_()
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.frame_pages.raise_()
        self.frame_left_menu.raise_()
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_toggle.clicked.connect(lambda: Ui_function.toggleMenu(self, 650, True))

    def onload(self):
        play =Player("hello buy dream ",'native')

        self.tableWidget.setColumnWidth(0, 150)
        self.tableWidget.setColumnWidth(1, 150)
        self.tableWidget_2.setColumnWidth(0, 150)
        self.tableWidget_2.setColumnWidth(1, 100)
        self.tableWidget_3.setColumnWidth(0, 250)
        self.tableWidget_3.setColumnWidth(1, 150)
        self.tableWidget_4.setColumnWidth(0, 150)
        self.tableWidget_4.setColumnWidth(1, 150)
        player=[]


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_toggle.setShortcut(_translate("MainWindow", "A"))
        self.EXIT.setShortcut(_translate("MainWindow", "Esc"))
        self.label_2.setText(_translate("MainWindow", "INCOME"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "interest dividends"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "investissement reel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "cash flow"))
        self.label.setText(_translate("MainWindow", "EXPENSES"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "interest dividends"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "investissement reel"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "cash flow"))
        self.label_5.setText(_translate("MainWindow", "INCREASE PASSIVE INCOME TO ESCAPE    THE RAT RAT RACE"))
        self.label_6.setText(_translate("MainWindow", "TOTAL EXPENSES:"))
        self.label_7.setText(_translate("MainWindow", "CASH :"))
        self.label_8.setText(_translate("MainWindow", "TOTAL INCOME :"))
        self.label_9.setText(_translate("MainWindow", "TOTAL EXPENSES :"))
        self.label_10.setText(_translate("MainWindow", "PAYDAY :"))
        self.CASH.setText(_translate("MainWindow", "$"))
        self.TOTAL_INCOME.setText(_translate("MainWindow", "$"))
        self.TOTAL_EXOENSE.setText(_translate("MainWindow", "$"))
        self.PAYDAY.setText(_translate("MainWindow", "$"))
        self.label_3.setText(_translate("MainWindow", "ASSETS                                                                    LIABILITIES"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STOCKS /Funds /CDs"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "$/Share"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("MainWindow", "Real Estate/Business"))
        item = self.tableWidget_3.item(3, 1)
        item.setText(_translate("MainWindow", "Cost"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "MAISON ENGAGE :"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Car Loans :"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Credit Cards :"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "investissement reel"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Real Estate/Businness"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(4, 0)
        item.setText(_translate("MainWindow", "Liability"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "CHAT LOG"))

import icons


class Mainwindow(QMainWindow):
        """docstring for Mainwindow"""

        def __init__(self):
                QMainWindow.__init__(self)
                self.showMaximized()
                self.ui = Ui_MainWindow()
                self.ui.setupUi(self)
                self.ui.btn_toggle.clicked.connect(lambda: Ui_function.toggleMenu(self, 1000, True))

                ## SHOW MAIN WINDOW

                self.show()


class Ui_function(Mainwindow):
        """docstring for Ui_function"""

        def toggleMenu(self, maxWidth, enable):
                self.onload()
                if enable:

                        # get width
                        width = self.frame_left_menu.width()
                        maxExtend = maxWidth
                        standard = 1
                        # set Mac Width
                        if width == 1:
                                widthExtended = maxExtend
                        else:
                                widthExtended = standard

                        # ANIMATION
                        self.animation = QPropertyAnimation(self.frame_left_menu, b"minimumWidth")
                        self.animation.setDuration(400)
                        self.animation.setStartValue(width)
                        self.animation.setEndValue(widthExtended)
                        self.animation.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
                        self.animation.start()

                pass
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

